[project]
name = "fastapi-uv-image-build"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10.17"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "uvicorn[standard]>=0.30.5",
]
